# Generated by Django 5.1.2 on 2024-10-27 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 10, 27, 13, 43, 51, 967879), verbose_name='Опубликована'),
        ),
    ]
