# Generated by Django 5.1.3 on 2024-11-28 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_product_image_url_product_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 28, 10, 12, 2, 840970), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 28, 10, 12, 2, 840970), verbose_name='Дата комментария'),
        ),
    ]
